apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs008-deployment
  namespace: default
  labels:
     app: cs008-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cs008-demo
  template:
    metadata:
      labels:
        app: cs008-demo
    spec:
      containers:
      - name: nodeapp008
        image: achyuth773/nodeapp008
---
apiVersion: v1
kind: Service
metadata:
  name: cs008-service
  namespace: default
  labels:
     app: cs008-demo
spec:
  type: NodePort
  selector:
     app: cs008-demo
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30008



